export const GET_LAPS_REQUEST = 'GET_LAPS_REQUEST';
export const GET_LAPS_SUCCESS = 'GET_LAPS_SUCCESS';
export const GET_LAPS_ERROR = 'GET_LAPS_ERROR';
export const SAVE_LAPS_REQUEST = 'SAVE_LAPS_REQUEST';
export const DELETE_LAPS_REQUEST = 'DELETE_LAPS_REQUEST';
